import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '..';
import Head from 'next/head';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/hack-fun/src/app/icons8-game-maker.svg" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
