import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link
          rel="icon"
          href="https://img.icons8.com/external-xnimrodx-lineal-gradient-xnimrodx/64/external-hack-encryption-xnimrodx-lineal-gradient-xnimrodx.png"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
